// Generated by Selenium IDE
using OpenQA.Selenium;
using NUnit.Framework;

namespace AngeloidTest.IntegrationSystem
{
    [TestFixture]
    public class ReviewAnimeTest : WebDriverSetUp
    {
        public static string[] AnimeReivewForm = new string[] {
            "This anime is wonderful with the story, the funny moment is enough humor, make viewers feel comfortable",
        };

        [Test]
        public void SearchByTextTestTrue([ValueSourceAttribute("BrowserToRunWith")] string browser, [ValueSourceAttribute("SearchByTextForm")] string review)
        {
            //Create web driver object
            Setup(browser);

            //Navigate to url
            webDriver.Navigate().GoToUrl("http://localhost:3000/");

            //Login to web
            webDriver.FindElement(By.LinkText("Login")).Click();
            webDriver.FindElement(By.Id("username")).Click();
            webDriver.FindElement(By.Id("username")).SendKeys("dbdbd9");
            webDriver.FindElement(By.Id("password")).Click();
            webDriver.FindElement(By.Id("password")).SendKeys("admin");
            webDriver.FindElement(By.Id("password")).SendKeys(Keys.Enter);

            //Find the anime to review
            webDriver.FindElement(By.CssSelector(".w-100:nth-child(3) .col-6:nth-child(2) > a > div:nth-child(1)")).Click();

            //Fill in the content of the review on the review form
            webDriver.FindElement(By.CssSelector(".form-control")).Click();
            webDriver.FindElement(By.CssSelector(".form-control")).SendKeys(review);

            // Post review
            webDriver.FindElement(By.CssSelector(".btn-success")).Click();
        }
    }
}